### ISSUE TITLE
cli "/o" output directory option is ignored

### ISSUE THREAD

**Issue by jarupxx** [Claybird/lhaforge#42]
"/o" オプションを受け入れますが LhaForge.ini の設定で上書きされてしまうようで機能しません。

https://github.com/Claybird/lhaforge/blob/develop/LhaForge/CommonUtil.cpp#L55-L73

**Comment by Claybird** [comment]
この件、もう少し情報をいただけないでしょうか。

9dd42ad35441f7170527e27a5afc9d243d583e4c と f0e7aa179de3ba80fef1f724ee49ec4a877af96a でテストを追加してみましたが、ご指摘の状態を再現できませんでした。

**Comment by Claybird** [comment]
parseExtractOptionにバグがあるのを発見しました

**Comment by Claybird** [comment]
411c58beee7cc87dd41ac45c1add20c2f3e76b31 にて修正しました

**Comment by jarupxx** [comment]
上手くいきました。ありがとうございます
