### ISSUE TITLE
Extract RAR archives bug

### ISSUE THREAD

**Issue by jarupxx** [Claybird/lhaforge#43]
RAR書庫を解凍すると指定した場所、元のファイルと同じ場所の二か所に解凍されてしまう。
RAR5、RAR4の両方で発生します。7zやzipでは不具合は生じません。

サンプルファイルをRAR5.rarにリネームしてください。
[(RAR5.rar.txt)](https://github.com/Claybird/lhaforge/files/13307377/RAR5.rar.txt)

・解凍時の出力先
　デスクトップ
・アーカイブ名の親フォルダ
　アーカイブ名の親フォルダを作成
・結果 二か所に解凍される
　デスクトップ\RAR5\書庫フォルダ\001.jpg
　元のファイルと同じ場所\書庫フォルダ\001.jpg

・解凍時の出力先
　元のファイルと同じ場所
・アーカイブ名の親フォルダ
　アーカイブ名の親フォルダを作成
・結果 二か所に解凍される
　書庫フォルダ\001.jpg
　RAR5\書庫フォルダ\001.jpg

・解凍時の出力先
　デスクトップ
・アーカイブ名の親フォルダ
　アーカイブ名の親フォルダは作成しない
・結果 二か所に解凍される
　デスクトップ\書庫フォルダ\001.jpg
　元のファイルと同じ場所\書庫フォルダ\001.jpg

・解凍時の出力先
　元のファイルと同じ場所
・アーカイブ名の親フォルダ
　アーカイブ名の親フォルダは作成しない
・結果 問題有り
　D:/書庫フォルダ -> directory created
　D:/書庫フォルダ/001.jpg -> Error creating file
　 -> Error creating file

**Comment by Claybird** [comment]
問題を確認し、 51e61b9df92325609f843c16044f242e4a4b1e38 にて修正しました。

**Comment by jarupxx** [comment]
ありがとうございました。
